### ISSUE TITLE
add a vignette describing how to use df_apply()

### ISSUE THREAD

**Issue by rpruim** [ashill1470/RPackProj#10]

**Comment by ashill1470** [comment]
I added df_apply()'s vignette. Not sure if it is working or I added it correctly though...

**Comment by rpruim** [comment]
Here are two ways to check:

1.  It should show up as an article in your pkgdown site.
2.  If you install with `devtools::install_github(..., build_vignettes = TRUE)`, then you should see the vignettes on your package help page or if you type (with your package name instead of `ggformula`):

``` r
vignette(package = "ggformula")
```

**Comment by rpruim** [comment]
I don't see a `docs/` folder in the repo.  When you use `pkgdown` to create your website, it should generate a bunch of files in `docs/`.  These need to be included in the repo so that github can serve them as a website.

You also need to adjust your repository settings (in the "pages" section) to tell github to serve that folder (from the main branch) as your GitHub pages website.
