### ISSUE TITLE
Add an example demoing use of ...

### ISSUE THREAD

**Issue by rpruim** [ashill1470/RPackProj#8]

**Comment by rpruim** [comment]
[round1-1.pdf](https://github.com/ashill1470/RPackProj/files/11074001/round1-1.pdf)
Note: Do not  write functions like

```r
my_filter <- function(x) is.numeric(x)
```

They serve no purpose. You can simply use `is.numeric()` directly without the wrapper function.

**Comment by ashill1470** [comment]
Added example in df_apply.R and df_apply() vignette.
